#ifndef _StretchController_h_
#define _StretchController_h_
/* -------------------------------------------------------------------------- *
 *                   OpenSim:  StretchController.h                    *
 * -------------------------------------------------------------------------- *
 * The OpenSim API is a toolkit for musculoskeletal modeling and simulation.  *
 * See http://opensim.stanford.edu and the NOTICE file for more information.  *
 * OpenSim is developed at Stanford University and supported by the US        *
 * National Institutes of Health (U54 GM072970, R24 HD065690) and by DARPA    *
 * through the Warrior Web program.                                           *
 *                                                                            *
 * Copyright (c) 2005-2016 Stanford University and the Authors                *
 * Author(s): Chris Dembia, Shrinidhi K. Lakshmikanth, Ajay Seth,             *
 *            Thomas Uchida                                                   *
 *                                                                            *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may    *
 * not use this file except in compliance with the License. You may obtain a  *
 * copy of the License at http://www.apache.org/licenses/LICENSE-2.0.         *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 * -------------------------------------------------------------------------- */


#include <OpenSim/OpenSim.h>

static const double COORDINATE_TARGET{ -0.1 };

using namespace std;
namespace OpenSim {

//------------------------------------------------------------------------------
// StretchController
//------------------------------------------------------------------------------
class StretchController : public Controller {
	OpenSim_DECLARE_CONCRETE_OBJECT(StretchController, Controller);

public:
	// Property of the controller for gain on the error signal
	OpenSim_DECLARE_PROPERTY(length_gain, double,
		"Gain used to convert length error to a control signal");

	// TODO threshold

	// Connector to the ScalarActuator for which the controller is computing a
	// control signal.
	OpenSim_DECLARE_CONNECTOR(actuator, ScalarActuator,
		"The actuator for which the controller is computing a control signal");

	// Input the muscle fiber length to use in the stretch controller
	OpenSim_DECLARE_INPUT(fiberLength, double, SimTK::Stage::Model,
		"The input length that is compared to the set point");

	// Input the set point for the muscle fiber length 
	OpenSim_DECLARE_INPUT(fiberLength_setpoint, double, SimTK::Stage::Model,
		"The set point on fiber length");

	// Output the control signal generated by the controller.
	OpenSim_DECLARE_OUTPUT(stretch_control, double, computeControl,
		SimTK::Stage::Time);

	StretchController() {
		constructProperties();
	}

	void updateTargetState(const SimTK::State& s) const {
		double setpoint = getInputValue<double>(s, "fiberLength_setpoint");

		//SimTK::State targetState = s;
		_internalModel->updCoordinateSet()[5].setValue(*_targetState, setpoint, false);
		_internalModel->realizePosition(*_targetState);
	}

	// Member function for computing the proportional control signal k*a.
	double computeControl(const SimTK::State& s) const
	{
		//Model m = getModel();
		//m.initSystem();
		//Model* _internalModel = &m;

		//double setpoint = getInputValue<double>(s, "fiberLength_setpoint");

		////SimTK::State targetState = s;
		//_internalModel->updCoordinateSet()[5].setValue(*_targetState, setpoint, false);
		//_internalModel->realizePosition(*_targetState);

		updateTargetState(s);


		Actuator& act = _internalModel->updActuators()[0];

		//cout << _internalModel->getBodySet()[0].getName();
		//cout << _targetGeometry->getFrame() << endl;
		//_targetFrame->updPosition = _internalModel->getBodySet()[0];

		const PathActuator* muscle1 = dynamic_cast<PathActuator*>(&act);
		double fiberLength_setPoint = muscle1->getLength(*_targetState);

		//double fiberLength_setPoint = getInputValue<double>(s,
		//	"fiberLength_setpoint");

		double fiberLength = getInputValue<double>(s, "fiberLength");

		//TODO: Design a control strategy that improves jump height.
		//return 0;
		double lengthError = fiberLength - fiberLength_setPoint;
		//cout << "len err " << lengthError << endl;
		//return (error < threshold) ? 0. : get_gain() * error;
		return get_length_gain() * lengthError;
	}

	// Member function for adding the control signal computed above into the
	// actuator's Vector of controls.
	void computeControls(const SimTK::State& s,
		SimTK::Vector& controls) const override
	{
		double signal = computeControl(s);
		const auto& actuator = getConnectee<ScalarActuator>("actuator");
		SimTK::Vector thisActuatorsControls(1, signal);
		actuator.addInControls(thisActuatorsControls, controls);
	}

	void setTargetState(SimTK::State* s) {
		_targetState = s;
	}

	void setInternalModel(Model* model) {
		_internalModel = model;
	}

	void setTargetGeometry(Geometry* geom) {
		_targetGeometry = geom;
	}

	void setTargetFrame(PhysicalOffsetFrame* frame) {
		_targetFrame = frame;
	}

private:
	void constructProperties() {
		constructProperty_length_gain(1.0);
	}

	void extendAddToSystem(SimTK::MultibodySystem& system) {
		Super::extendAddToSystem(system);

		//_internalModel = getModel().clone();

		//if (_internalModel == NULL) {
		//	Model im = getModel().clone();
		//	_internalModel = im.clone();
		//}

		//Model im = getModel();
		//SimTK::State saveState = s;
		//im.getCoordinateSet()[0].getValue(s);

		//_internalModel->initStateWithoutRecreatingSystem(s);

	}

	// Implement generateDecorations by WrapSphere to replace the previous out of place implementation 
	// in ModelVisualizer
	void generateDecorations(bool fixed, const ModelDisplayHints& hints, const SimTK::State& state,
		SimTK::Array_<SimTK::DecorativeGeometry>& appendToThis) const
	{
		Super::generateDecorations(fixed, hints, state, appendToThis);
		if (fixed) return;

		updateTargetState(state);

		const SimTK::Vec3 color(SimTK::Cyan);
		const SimTK::Transform& X_GW = getModel().getBodySet()[0].getTransformInGround(*_targetState);
		//Geometry& geom = *(getModel().getBodySet()[0].get_attached_geometry(0).clone());
		// TODO get correct geometry from the model
		appendToThis.push_back(
				SimTK::DecorativeSphere(0.1)
				.setTransform(X_GW).setResolution(2.0)
				.setColor(color).setOpacity(0.5));
	}

	Model* _internalModel;
	SimTK::State* _targetState;
	Geometry* _targetGeometry;
	PhysicalOffsetFrame* _targetFrame;

}; // end of StretchController


} // end of namespace OpenSim

#endif // _StretchController_h_
